import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, Bell, Check, ChevronRight, CreditCard, Gem, LayoutDashboard, LifeBuoy, LockKeyhole, Package, PanelLeft, RefreshCw, Search, Settings2, ShieldCheck, ShoppingCart, Sparkles, Users, WalletCards, X } from "lucide-react";
import { CATALOG } from "@/lib/catalog";

export const Route=createFileRoute("/admin")({component:AdminPage});

type View="overview"|"orders"|"products"|"customers"|"payments"|"crypto"|"wallet"|"promotions"|"support"|"analytics"|"security"|"audit"|"staff";
type Data={ok:boolean;stats:{orders:number;paidOrders:number;revenue:number;pending:number;customers:number};orders:any[];customers:any[];stock:any[];promotions:any[];staff:any[];audit:any[];security:any[]};
const navGroups:any[]=[
 {label:"Workspace",items:[["overview","Overview",LayoutDashboard],["orders","Orders",ShoppingCart],["products","Products",Package],["customers","Customers",Users],["payments","Payments",CreditCard],["crypto","Crypto queue",Gem],["wallet","Wallet",WalletCards],["promotions","Promotions",Sparkles],["support","Support",LifeBuoy]]},
 {label:"Control room",items:[["analytics","Analytics",BarChart3],["security","Security",ShieldCheck],["audit","Audit logs",PanelLeft],["staff","Staff & access",Settings2]]}
];

async function api(action?:any){const r=await fetch("/api/public/admin",{method:action?"POST":"GET",headers:action?{"content-type":"application/json"}:undefined,credentials:"same-origin",body:action?JSON.stringify(action):undefined});const j=await r.json().catch(()=>({ok:false,error:"invalid_response"}));if(!r.ok)throw new Error(j.error||"forbidden");return j;}

function AdminPage(){
 const [view,setView]=useState<View>("overview"),[mobile,setMobile]=useState(false),[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=async()=>{try{setError("");setData(await api())}catch(e){setError(e instanceof Error?e.message:"Access denied")}};
 useEffect(()=>{load()},[]);
 if(error)return <div className="admin-app"><main className="admin-content"><Panel><div className="admin-empty"><LockKeyhole size={30}/><strong>Admin access required</strong><span>This account is not authorized to access BloxStar operations.</span></div></Panel></main></div>;
 if(!data)return <div className="admin-app"><main className="admin-content"><Panel><div className="admin-empty"><RefreshCw size={25}/><strong>Loading secure admin workspace…</strong></div></Panel></main></div>;
 const go=(v:View)=>{setView(v);setMobile(false)};
 return <div className="admin-app">
  <aside className={`admin-sidebar ${mobile?"is-open":""}`}>
   <div className="admin-brand"><span className="admin-mark">B</span><span>BloxStar <b>/ ops</b></span><button className="admin-mobile-close" onClick={()=>setMobile(false)}><X size={18}/></button></div>
   <div className="admin-nav">{navGroups.map(g=><div key={g.label}><p className="admin-nav-label">{g.label}</p>{g.items.map(([id,label,Icon]:any)=><button key={id} className={`admin-nav-item ${view===id?"active":""}`} onClick={()=>go(id)}><Icon size={17}/><span>{label}</span></button>)}</div>)}</div>
   <div className="admin-operator"><span className="admin-avatar">AD</span><div><strong>{data.staff?.find((s:any)=>s.status==="active")?.name||"Admin"}</strong><small>AUTHORIZED · LIVE</small></div></div>
  </aside>
  {mobile&&<button className="admin-overlay" onClick={()=>setMobile(false)} aria-label="Close navigation"/>}
  <div className="admin-main"><header className="admin-topbar"><button className="admin-menu-button" onClick={()=>setMobile(true)}><span>☰</span></button><div className="admin-breadcrumb"><span>Workspace</span><b>/</b><strong>{labelFor(view)}</strong></div><div className="admin-top-actions"><span className="admin-production"><i/> Production</span><button className="admin-icon-button" onClick={()=>load()} aria-label="Refresh"><Bell size={18}/></button></div></header>
   <main className="admin-content">{notice&&<div className="admin-notice"><Check size={16}/>{notice}<button onClick={()=>setNotice("")}><X size={14}/></button></div>}
    {view==="overview"&&<Overview data={data} go={go}/>} {view==="orders"&&<Orders data={data} refresh={load} notice={setNotice}/>}
    {view==="products"&&<Products data={data}/>} {view==="customers"&&<Customers data={data}/>} {view==="payments"&&<Payments data={data}/>}
    {view==="crypto"&&<Crypto data={data}/>} {view==="wallet"&&<Wallet data={data}/>} {view==="promotions"&&<Promotions data={data} refresh={load} notice={setNotice}/>}
    {view==="support"&&<Support data={data}/>} {view==="analytics"&&<Analytics data={data}/>} {view==="security"&&<Security data={data}/>}
    {view==="audit"&&<Audit data={data}/>} {view==="staff"&&<Staff data={data} refresh={load} notice={setNotice}/>}
   </main></div>
 </div>
}
const labelFor=(v:View)=>v==="crypto"?"Crypto queue":v==="audit"?"Audit logs":v==="staff"?"Staff & access":v[0].toUpperCase()+v.slice(1);
function Panel({children,className=""}:{children:any;className?:string}){return <section className={`admin-panel ${className}`}>{children}</section>}
function Heading({title,detail,action}:{title:string;detail:string;action?:any}){return <div className="admin-heading"><div><p>LIVE / NEON</p><h1>{title}</h1><span>{detail}</span></div>{action}</div>}
function Button({children,onClick,secondary=false}:{children:any;onClick?:()=>void;secondary?:boolean}){return <button className={`admin-button ${secondary?"secondary":""}`} onClick={onClick}>{children}</button>}
function Badge({children}:{children:any}){return <span className={`admin-badge ${String(children).toLowerCase().replaceAll(" ","-")}`}>{children}</span>}
function Overview({data,go}:{data:Data;go:(v:View)=>void}){
 const paid=data.orders.filter(o=>o.paid), recent=data.orders.slice(0,8);
 return <><Heading title="Operations overview" detail="Live metrics from the existing Neon database." action={<Button secondary onClick={()=>location.reload()}><RefreshCw size={15}/> Refresh</Button>}/>
 <div className="admin-metrics"><Metric label="Revenue" value={`$${data.stats.revenue.toFixed(2)}`} icon="$"/><Metric label="Orders" value={String(data.stats.orders)} icon="↗"/><Metric label="Paid orders" value={String(data.stats.paidOrders)} icon="✓"/><Metric label="Customers" value={String(data.stats.customers)} icon="◎"/></div>
 <div className="admin-grid-two"><Panel><PanelTitle title="Order health"/><div className="admin-progress-list">{[["Paid",paid.length],["Pending / processing",data.stats.pending],["Cancelled",data.orders.filter(o=>o.status==="cancelled").length]].map(([x,n])=><div key={String(x)}><label><span>{x}</span><b>{n}</b></label><i style={{width:`${Math.min(100,Number(n)/(Math.max(1,data.stats.orders))*100)}%`}}/></div>)}</div></Panel>
 <Panel><PanelTitle title="Recent orders" action={<button className="admin-link" onClick={()=>go("orders")}>SEE ALL <ChevronRight size={13}/></button>}/>{recent.slice(0,5).map(o=><OrderRow key={o.code} o={o}/>)}</Panel></div>
 <Panel><PanelTitle title="Catalog"/><p className="admin-subtitle">{CATALOG.length} server-owned products. Stock rows loaded from Neon.</p></Panel></>
}
function Metric({label,value,icon}:{label:string;value:string;icon:string}){return <div className="admin-metric"><span className="admin-metric-icon">{icon}</span><small>{label}</small><strong>{value}</strong></div>}
function PanelTitle({title,action}:{title:string;action?:any}){return <div className="admin-panel-title"><h2>{title}</h2>{action}</div>}
function OrderRow({o}:{o:any}){return <div className="admin-order-row"><span className="admin-avatar small">{String(o.email||"??").slice(0,2).toUpperCase()}</span><div><strong>{o.email||"Guest"}</strong><small>#{o.code} · {o.createdAt?new Date(o.createdAt).toLocaleString():""}</small></div><b>${Number(o.total).toFixed(2)}</b><Badge>{o.status}</Badge></div>}
function Orders({data,refresh,notice}:{data:Data;refresh:()=>void;notice:(x:string)=>void}){
 const [q,setQ]=useState(""),[sel,setSel]=useState<any>(null);const rows=data.orders.filter(o=>`${o.code} ${o.email} ${o.robloxUser}`.toLowerCase().includes(q.toLowerCase()));
 const change=async(status:string)=>{if(!sel||!confirm(`Set ${sel.code} to ${status}?`))return;try{await api({action:"order_status",code:sel.code,status});notice("Order updated and audit log created.");await refresh();setSel({...sel,status})}catch(e){notice(e instanceof Error?e.message:"Update failed")}};
 return <><Heading title="Orders" detail={`${data.orders.length} real orders from Neon.`}/><div className="admin-toolbar"><label><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search order, email or Roblox name…"/></label></div><div className="admin-split"><Panel className="admin-list-panel">{rows.slice(0,200).map(o=><button className={`admin-order-card ${sel?.code===o.code?"selected":""}`} key={o.code} onClick={()=>setSel(o)}><span className="admin-avatar small">{String(o.email||"??").slice(0,2).toUpperCase()}</span><div><strong>{o.email||"Guest"}</strong><small>#{o.code} · {o.robloxUser||"No Roblox name"}</small></div><div className="admin-order-meta"><b>${Number(o.total).toFixed(2)}</b><small>{o.game}</small></div><Badge>{o.status}</Badge><ChevronRight size={16}/></button>)}</Panel><Panel className="admin-detail">{sel?<><div className="admin-detail-head"><div><p className="admin-kicker">Order detail</p><h2>#{sel.code}</h2><span>{sel.email} · {sel.robloxUser}</span></div><Badge>{sel.status}</Badge></div><div className="admin-detail-total"><span>{sel.items?.map((i:any)=>i.n||i.name).join(", ")||"Items"}</span><b>${Number(sel.total).toFixed(2)}</b></div><div className="admin-action-row"><Button onClick={()=>change("processing")}>Processing</Button><Button secondary onClick={()=>change("delivered")}>Complete</Button><Button secondary onClick={()=>change("cancelled")}>Cancel</Button></div></>:<div className="admin-empty"><ShoppingCart size={24}/><strong>Select an order</strong></div>}</Panel></div></>
}
function Products({data}:{data:Data}){const [q,setQ]=useState("");const stock=new Map(data.stock.map((x:any)=>[Number(x.item_id),Number(x.qty)]));const rows=CATALOG.filter(x=>`${x.id} ${x.n}`.toLowerCase().includes(q.toLowerCase()));return <><Heading title="Products" detail={`${CATALOG.length} products from the server catalog. Prices are read-only here.`}/><div className="admin-toolbar"><label><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search product…"/></label></div><Panel className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Item</th><th>Game</th><th>Price</th><th>Stock</th><th>State</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.n}</strong><small>#{x.id}</small></td><td>{x.g}</td><td>${x.p.toFixed(2)}</td><td>{stock.has(x.id)?stock.get(x.id):"—"}</td><td><Badge>{x.a?"Active":"Inactive"}</Badge></td></tr>)}</tbody></table></Panel></>}
function Customers({data}:{data:Data}){return <><Heading title="Customers" detail={`${data.customers.length} customer records derived from real orders.`}/><Panel className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Email</th><th>Orders</th><th>Spend</th><th>Last order</th></tr></thead><tbody>{data.customers.map((x:any)=><tr key={x.email}><td>{x.email}</td><td>{x.orders}</td><td>${Number(x.spend).toFixed(2)}</td><td>{x.last_order?new Date(x.last_order).toLocaleString():"—"}</td></tr>)}</tbody></table></Panel></>}
function Payments({data}:{data:Data}){const rows=data.orders.filter(o=>o.paid||o.data?.pay);return <><Heading title="Payments" detail="Payment records sourced from Neon orders."/><Panel className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Method</th><th>Amount</th><th>Status</th></tr></thead><tbody>{rows.map(o=><tr key={o.code}><td>#{o.code}<small>{o.email}</small></td><td>{o.data?.pay||"Order payment"}</td><td>${Number(o.total).toFixed(2)}</td><td><Badge>{o.paid?"Paid":o.status}</Badge></td></tr>)}</tbody></table></Panel></>}
function Crypto({data}:{data:Data}){const rows=data.orders.filter(o=>String(o.data?.pay||"").toLowerCase().includes("crypto")||String(o.data?.payment||"").toLowerCase().includes("crypto"));return <><Heading title="Crypto queue" detail={`${rows.length} crypto-related orders currently visible.`}/><Panel className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Email</th><th>Total</th><th>Status</th></tr></thead><tbody>{rows.map(o=><tr key={o.code}><td>#{o.code}</td><td>{o.email}</td><td>${Number(o.total).toFixed(2)}</td><td><Badge>{o.status}</Badge></td></tr>)}</tbody></table></Panel></>}
function Wallet({data}:{data:Data}){return <><Heading title="Wallet" detail="Wallet ledger and balances are kept in Neon."/><Panel><PanelTitle title="Wallet records"/><p className="admin-subtitle">The existing wallet API remains the source of truth. This workspace does not invent balances or mutate them.</p></Panel></>}
function Promotions({data,refresh,notice}:{data:Data;refresh:()=>void;notice:(x:string)=>void}){const [code,setCode]=useState(""),[offer,setOffer]=useState("");return <><Heading title="Promotions" detail={`${data.promotions.length} real promotion records.`}/><Panel><PanelTitle title="Create / update promotion"/><div className="admin-toolbar"><input placeholder="CODE" value={code} onChange={e=>setCode(e.target.value)}/><input placeholder="Offer" value={offer} onChange={e=>setOffer(e.target.value)}/><Button onClick={async()=>{try{await api({action:"promotion",code,offer});setCode("");setOffer("");await refresh();notice("Promotion saved.")}catch(e){notice(e instanceof Error?e.message:"Failed")}}}>Save</Button></div></Panel><Panel className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Code</th><th>Offer</th><th>Usage</th><th>State</th></tr></thead><tbody>{data.promotions.map((x:any)=><tr key={x.code}><td>{x.code}</td><td>{x.offer}</td><td>{x.usage_count}/{x.usage_limit||"∞"}</td><td><button onClick={async()=>{await api({action:"promotion_toggle",code:x.code});await refresh()}}><Badge>{x.enabled?"Enabled":"Disabled"}</Badge></button></td></tr>)}</tbody></table></Panel></>}
function Support({data}:{data:Data}){return <><Heading title="Support" detail="No fake tickets are shown. Existing order/customer data is available for support workflows."/><Panel><div className="admin-empty"><LifeBuoy size={25}/><strong>No support ticket table exists in the current production schema.</strong><span>Nothing is fabricated; add a support-ticket migration when you want ticket storage.</span></div></Panel></>}
function Analytics({data}:{data:Data}){const games=[...new Set(data.orders.map(o=>o.game||"unknown"))]; return <><Heading title="Analytics" detail="Calculated from real Neon order data."/><div className="admin-metrics">{games.map(g=><Metric key={g} label={g} value={String(data.orders.filter(o=>(o.game||"unknown")===g).length)} icon="•"/>)}</div><Panel><PanelTitle title="Paid revenue by game"/>{games.map(g=>{const revenue=data.orders.filter(o=>(o.game||"unknown")===g&&o.paid).reduce((sum,o)=>sum+Number(o.total),0); return <p key={g}>{g}: ${revenue.toFixed(2)}</p>})}</Panel></>}
function Security({data}:{data:Data}){return <><Heading title="Security" detail="Real security events recorded by the admin API."/><Panel className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Time</th><th>Severity</th><th>Event</th><th>Actor</th></tr></thead><tbody>{data.security.map((x:any)=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString()}</td><td><Badge>{x.severity}</Badge></td><td>{x.event_type}</td><td>{x.actor_email||"system"}</td></tr>)}</tbody></table></Panel></>}
function Audit({data}:{data:Data}){return <><Heading title="Audit logs" detail="Protected admin actions are written server-side."/><Panel className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Time</th><th>Admin</th><th>Action</th><th>Resource</th></tr></thead><tbody>{data.audit.map((x:any)=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString()}</td><td>{x.admin_email}</td><td>{x.action}</td><td>{x.resource||"—"}</td></tr>)}</tbody></table></Panel></>}
function Staff({data,refresh,notice}:{data:Data;refresh:()=>void;notice:(x:string)=>void}){const [email,setEmail]=useState(""),[name,setName]=useState(""),[role,setRole]=useState("support");return <><Heading title="Staff & access" detail="Only active staff or ADMIN_EMAILS can pass the server-side gate."/><Panel><div className="admin-toolbar"><input placeholder="email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="name" value={name} onChange={e=>setName(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)}><option>support</option><option>moderator</option><option>finance</option><option>product</option><option>owner</option></select><Button onClick={async()=>{try{await api({action:"staff",email,name,role});await refresh();notice("Staff member saved.")}catch(e){notice(e instanceof Error?e.message:"Failed")}}}>Add staff</Button></div></Panel><Panel className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Email</th><th>Name</th><th>Role</th><th>Status</th></tr></thead><tbody>{data.staff.map((x:any)=><tr key={x.email}><td>{x.email}</td><td>{x.name||"—"}</td><td>{x.role}</td><td><Badge>{x.status}</Badge></td></tr>)}</tbody></table></Panel></>}
