import { createFileRoute } from "@tanstack/react-router";
import { cookieValue, SESSION_COOKIE, isAdminEmail } from "@/lib/auth";
import { jsonResponse, preflight, safeHandler, sameOrigin } from "@/lib/http";
import { clientIp, distributedRateLimit } from "@/lib/rate-limit";
const MAX_AMOUNT=5000, WHEEL_PRIZES=[1,5], WHEEL_COOLDOWN_MS=12*3600*1000;
const round2=(n:number)=>Math.round(n*100)/100;
const amountOf=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)&&n>0?round2(Math.min(n,MAX_AMOUNT)):0};
const database=async()=> (await import("@/lib/db")).db(); type Sql=Awaited<ReturnType<typeof database>>;
type Session={email:string;admin:boolean}|null;
async function sessionFor(sql:Sql,request:Request):Promise<Session>{const token=cookieValue(request,SESSION_COOKIE);if(!token)return null;const r=(await sql`SELECT email,admin,expires_at FROM auth_sessions WHERE token=${token} LIMIT 1`) as Array<{email:string;admin:boolean;expires_at:string}>;const x=r[0];if(!x||new Date(x.expires_at).getTime()<Date.now())return null;return {email:x.email.toLowerCase(),admin:isAdminEmail(x.email)};}
async function ensureWalletSchema(sql:Sql){
  await sql`CREATE TABLE IF NOT EXISTS wallets(email text PRIMARY KEY,balance numeric(12,2) NOT NULL DEFAULT 0,updated_at timestamptz NOT NULL DEFAULT now())`;
  await sql`CREATE TABLE IF NOT EXISTS wallet_tx(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),email text NOT NULL,kind text NOT NULL,amount numeric(12,2) NOT NULL,note text NOT NULL DEFAULT '',ref text,created_at timestamptz NOT NULL DEFAULT now())`;
  await sql`CREATE INDEX IF NOT EXISTS wallet_tx_email_idx ON wallet_tx(email,created_at DESC)`; await sql`CREATE UNIQUE INDEX IF NOT EXISTS wallet_tx_ref_idx ON wallet_tx(ref) WHERE ref IS NOT NULL`;
  await sql`CREATE TABLE IF NOT EXISTS gift_cards(code text PRIMARY KEY,amount numeric(12,2) NOT NULL,redeemed_by text,redeemed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now())`;
  await sql`INSERT INTO gift_cards(code,amount) VALUES ('BLOX-10',10),('BLOX-25',25),('STAR-50',50) ON CONFLICT(code) DO NOTHING`;
  await sql`CREATE TABLE IF NOT EXISTS wallet_withdrawals(id text PRIMARY KEY,email text NOT NULL,amount numeric(12,2) NOT NULL,method text NOT NULL DEFAULT '',dest text NOT NULL DEFAULT '',status text NOT NULL DEFAULT 'pending',created_at timestamptz NOT NULL DEFAULT now())`;
  await sql`CREATE OR REPLACE FUNCTION wallet_spend(p_email text,p_amount numeric,p_kind text,p_note text,p_ref text) RETURNS numeric LANGUAGE plpgsql AS $$ DECLARE b numeric; BEGIN UPDATE wallets SET balance=balance-p_amount,updated_at=now() WHERE email=p_email AND balance>=p_amount RETURNING balance INTO b; IF b IS NULL THEN RAISE EXCEPTION 'insufficient_funds'; END IF; INSERT INTO wallet_tx(email,kind,amount,note,ref) VALUES(p_email,p_kind,-p_amount,left(p_note,200),p_ref); RETURN b; END; $$`;
  await sql`CREATE OR REPLACE FUNCTION wallet_credit(p_email text,p_amount numeric,p_kind text,p_note text,p_ref text) RETURNS numeric LANGUAGE plpgsql AS $$ DECLARE b numeric; BEGIN IF p_ref IS NOT NULL AND EXISTS(SELECT 1 FROM wallet_tx WHERE ref=p_ref) THEN SELECT balance INTO b FROM wallets WHERE email=p_email; RETURN COALESCE(b,0); END IF; INSERT INTO wallets(email,balance) VALUES(p_email,p_amount) ON CONFLICT(email) DO UPDATE SET balance=wallets.balance+p_amount,updated_at=now() RETURNING balance INTO b; INSERT INTO wallet_tx(email,kind,amount,note,ref) VALUES(p_email,p_kind,p_amount,left(p_note,200),p_ref) ON CONFLICT DO NOTHING; RETURN b; END; $$`;
  await sql`CREATE OR REPLACE FUNCTION wallet_redeem_gift(p_email text,p_code text) RETURNS numeric LANGUAGE plpgsql AS $$ DECLARE a numeric; b numeric; BEGIN UPDATE gift_cards SET redeemed_by=p_email,redeemed_at=now() WHERE code=p_code AND redeemed_by IS NULL RETURNING amount INTO a; IF a IS NULL THEN RAISE EXCEPTION 'invalid_or_used'; END IF; INSERT INTO wallets(email,balance) VALUES(p_email,a) ON CONFLICT(email) DO UPDATE SET balance=wallets.balance+a,updated_at=now() RETURNING balance INTO b; INSERT INTO wallet_tx(email,kind,amount,note,ref) VALUES(p_email,'giftcard',a,'Gift card '||p_code,'gift:'||p_code); RETURN b; END; $$`;
  await sql`CREATE OR REPLACE FUNCTION wallet_withdraw_atomic(p_id text,p_email text,p_amount numeric,p_method text,p_dest text) RETURNS numeric LANGUAGE plpgsql AS $$ DECLARE b numeric; BEGIN UPDATE wallets SET balance=balance-p_amount,updated_at=now() WHERE email=p_email AND balance>=p_amount RETURNING balance INTO b; IF b IS NULL THEN RAISE EXCEPTION 'insufficient_funds'; END IF; INSERT INTO wallet_withdrawals(id,email,amount,method,dest) VALUES(p_id,p_email,p_amount,left(p_method,40),left(p_dest,200)); INSERT INTO wallet_tx(email,kind,amount,note,ref) VALUES(p_email,'withdraw',-p_amount,'Withdrawal · '||upper(left(p_method,40)),'withdraw:'||p_id); RETURN b; END; $$`;
  await sql`CREATE OR REPLACE FUNCTION wallet_reward(p_email text,p_amount numeric) RETURNS numeric LANGUAGE plpgsql AS $$ DECLARE last_at timestamptz; b numeric; BEGIN SELECT created_at INTO last_at FROM wallet_tx WHERE email=p_email AND kind='wheel' ORDER BY created_at DESC LIMIT 1; IF last_at IS NOT NULL AND last_at>now()-interval '12 hours' THEN RAISE EXCEPTION 'cooldown'; END IF; INSERT INTO wallets(email,balance) VALUES(p_email,p_amount) ON CONFLICT(email) DO UPDATE SET balance=wallets.balance+p_amount,updated_at=now() RETURNING balance INTO b; INSERT INTO wallet_tx(email,kind,amount,note) VALUES(p_email,'wheel',p_amount,'Wheel of Fortune prize'); RETURN b; END; $$`;
}
async function balanceOf(sql:Sql,email:string){const r=(await sql`SELECT balance FROM wallets WHERE email=${email} LIMIT 1`) as Array<{balance:string}>;return round2(Number(r[0]?.balance??0));}
async function historyOf(sql:Sql,email:string){const r=(await sql`SELECT kind,amount,note,created_at FROM wallet_tx WHERE email=${email} ORDER BY created_at DESC LIMIT 40`) as Array<{kind:string;amount:string;note:string;created_at:string}>;return r.map(x=>({t:x.kind,a:Number(x.amount),n:x.note||x.kind,at:new Date(x.created_at).getTime()}));}
export const Route=createFileRoute("/api/public/wallet")({server:{handlers:{OPTIONS:async({request})=>preflight(request),POST:async({request})=>safeHandler(request,"wallet",async()=>{
  const json=(b:unknown,s=200)=>jsonResponse(request,b,s); if(!sameOrigin(request))return json({ok:false,error:"forbidden"},403); let body:Record<string,unknown>;try{body=(await request.json()) as Record<string,unknown>}catch{return json({ok:false,error:"bad_request"},400)}
  if(!process.env.DATABASE_URL)return json({ok:false,error:"wallet_unavailable"},503); const {ensureAuthSchema}=await import("@/lib/db");await ensureAuthSchema();const sql=await database();await ensureWalletSchema(sql);const session=await sessionFor(sql,request);if(!session)return json({ok:false,error:"unauthorized"},401);
  if(!(await distributedRateLimit(sql,`wallet:${clientIp(request)}:${session.email}`,60,60000)))return json({ok:false,error:"rate_limited"},429);
  const email=session.email, action=String(body.action??"get").toLowerCase(); const state=async(extra:Record<string,unknown>={})=>json({ok:true,email,balance:await balanceOf(sql,email),history:await historyOf(sql,email),...extra});
  if(action==="get")return state();
  if(action==="spend"){const a=amountOf(body.amount);if(!a)return json({ok:false,error:"bad_amount"},400);try{const ref='spend:'+crypto.randomUUID();const r=(await sql`SELECT wallet_spend(${email},${a},${String(body.kind??"order").slice(0,40)},${String(body.note??"Paid with balance").slice(0,200)},${ref}) AS balance`) as Array<{balance:string}>;return state();}catch(e){if(String(e).includes('insufficient_funds'))return json({ok:false,error:"insufficient_funds",balance:await balanceOf(sql,email)},400);throw e;}}
  if(action==="withdraw"){const a=amountOf(body.amount),method=String(body.method??"").slice(0,40),dest=String(body.dest??"").trim().slice(0,200);if(!a)return json({ok:false,error:"bad_amount"},400);if(!dest)return json({ok:false,error:"missing_destination"},400);const id='WD'+crypto.randomUUID().replace(/-/g,'').slice(0,24);try{await sql`SELECT wallet_withdraw_atomic(${id},${email},${a},${method},${dest})`;return state({withdrawalId:id});}catch(e){if(String(e).includes('insufficient_funds'))return json({ok:false,error:"insufficient_funds",balance:await balanceOf(sql,email)},400);throw e;}}
  if(action==="giftcard"){const code=String(body.code??"").trim().toUpperCase().slice(0,40);if(!code)return json({ok:false,error:"bad_code"},400);try{const r=(await sql`SELECT wallet_redeem_gift(${email},${code}) AS balance`) as Array<{balance:string}>;return state({credited:await balanceOf(sql,email)});}catch(e){if(String(e).includes('invalid_or_used'))return json({ok:false,error:"invalid_or_used"},400);throw e;}}
  if(action==="reward"){const a=amountOf(body.amount);if(!WHEEL_PRIZES.includes(a))return json({ok:false,error:"bad_amount"},400);try{await sql`SELECT wallet_reward(${email},${a})`;return state({credited:a});}catch(e){if(String(e).includes('cooldown'))return json({ok:false,error:"cooldown",balance:await balanceOf(sql,email)},429);throw e;}}
  if(!session.admin)return json({ok:false,error:"forbidden"},403); const target=String(body.email??"").trim().toLowerCase().slice(0,200);if(!target)return json({ok:false,error:"missing_email"},400);
  if(action==="lookup")return json({ok:true,email:target,balance:await balanceOf(sql,target),history:await historyOf(sql,target)});
  if(action==="credit"){const a=amountOf(body.amount);if(!a)return json({ok:false,error:"bad_amount"},400);const ref=String(body.ref??"").trim().slice(0,120)||null;const r=(await sql`SELECT wallet_credit(${target},${a},'topup',${String(body.note??"Balance added").slice(0,200)},${ref}) AS balance`) as Array<{balance:string}>;return json({ok:true,email:target,balance:Number(r[0]?.balance??0)});}
  if(action==="adjust"){const value=round2(Math.max(0,Math.min(MAX_AMOUNT,Number(body.balance)||0)));await sql`INSERT INTO wallets(email,balance) VALUES(${target},${value}) ON CONFLICT(email) DO UPDATE SET balance=${value},updated_at=now()`;await sql`INSERT INTO wallet_tx(email,kind,amount,note,ref) VALUES(${target},'adjust',0,${`Balance set to ${value} by ${email}`},${'adjust:'+crypto.randomUUID()})`;return json({ok:true,email:target,balance:value});}
  return json({ok:false,error:"unknown_action"},400);
})}}});
