/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdoptMeRouteImport } from './routes/adopt-me'
import { Route as GrowAGardenRouteImport } from './routes/grow-a-garden'
import { Route as Mm2RouteImport } from './routes/mm2'
import { Route as RobloxItemsRouteImport } from './routes/roblox-items'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicAbandonedCartRouteImport } from './routes/api/public/abandoned-cart'
import { Route as ApiPublicAccountRouteImport } from './routes/api/public/account'
import { Route as ApiPublicAdminRouteImport } from './routes/api/public/admin'
import { Route as ApiPublicOrdersRouteImport } from './routes/api/public/orders'
import { Route as ApiPublicWalletRouteImport } from './routes/api/public/wallet'
import { Route as AuthGoogleStartRouteImport } from './routes/auth.google.start'
import { Route as ApiPublicAuthHealthRouteImport } from './routes/api/public/auth.health'
import { Route as ApiPublicAuthSendCodeRouteImport } from './routes/api/public/auth.send-code'
import { Route as ApiPublicAuthSessionRouteImport } from './routes/api/public/auth.session'
import { Route as ApiPublicAuthVerifyCodeRouteImport } from './routes/api/public/auth.verify-code'
import { Route as ApiPublicEmailSendRouteImport } from './routes/api/public/email.send'
import { Route as ApiPublicAuthGoogleCallbackRouteImport } from './routes/api/public/auth.google.callback'
import { Route as ApiPublicAuthGoogleExchangeRouteImport } from './routes/api/public/auth.google.exchange'
import { Route as ApiPublicAuthGoogleStartRouteImport } from './routes/api/public/auth.google.start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdoptMeRoute = AdoptMeRouteImport.update({
  id: '/adopt-me',
  path: '/adopt-me',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowAGardenRoute = GrowAGardenRouteImport.update({
  id: '/grow-a-garden',
  path: '/grow-a-garden',
  getParentRoute: () => rootRouteImport,
} as any)
const Mm2Route = Mm2RouteImport.update({
  id: '/mm2',
  path: '/mm2',
  getParentRoute: () => rootRouteImport,
} as any)
const RobloxItemsRoute = RobloxItemsRouteImport.update({
  id: '/roblox-items',
  path: '/roblox-items',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAbandonedCartRoute = ApiPublicAbandonedCartRouteImport.update({
  id: '/api/public/abandoned-cart',
  path: '/api/public/abandoned-cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAccountRoute = ApiPublicAccountRouteImport.update({
  id: '/api/public/account',
  path: '/api/public/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminRoute = ApiPublicAdminRouteImport.update({
  id: '/api/public/admin',
  path: '/api/public/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrdersRoute = ApiPublicOrdersRouteImport.update({
  id: '/api/public/orders',
  path: '/api/public/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWalletRoute = ApiPublicWalletRouteImport.update({
  id: '/api/public/wallet',
  path: '/api/public/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleStartRoute = AuthGoogleStartRouteImport.update({
  id: '/auth/google/start',
  path: '/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthHealthRoute = ApiPublicAuthHealthRouteImport.update({
  id: '/api/public/auth/health',
  path: '/api/public/auth/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthSendCodeRoute = ApiPublicAuthSendCodeRouteImport.update({
  id: '/api/public/auth/send-code',
  path: '/api/public/auth/send-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthSessionRoute = ApiPublicAuthSessionRouteImport.update({
  id: '/api/public/auth/session',
  path: '/api/public/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthVerifyCodeRoute = ApiPublicAuthVerifyCodeRouteImport.update({
  id: '/api/public/auth/verify-code',
  path: '/api/public/auth/verify-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailSendRoute = ApiPublicEmailSendRouteImport.update({
  id: '/api/public/email/send',
  path: '/api/public/email/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthGoogleCallbackRoute =
  ApiPublicAuthGoogleCallbackRouteImport.update({
    id: '/api/public/auth/google/callback',
    path: '/api/public/auth/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthGoogleExchangeRoute =
  ApiPublicAuthGoogleExchangeRouteImport.update({
    id: '/api/public/auth/google/exchange',
    path: '/api/public/auth/google/exchange',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthGoogleStartRoute =
  ApiPublicAuthGoogleStartRouteImport.update({
    id: '/api/public/auth/google/start',
    path: '/api/public/auth/google/start',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adopt-me': typeof AdoptMeRoute
  '/grow-a-garden': typeof GrowAGardenRoute
  '/mm2': typeof Mm2Route
  '/roblox-items': typeof RobloxItemsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/abandoned-cart': typeof ApiPublicAbandonedCartRoute
  '/api/public/account': typeof ApiPublicAccountRoute
  '/api/public/admin': typeof ApiPublicAdminRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
  '/api/public/wallet': typeof ApiPublicWalletRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
  '/api/public/auth/health': typeof ApiPublicAuthHealthRoute
  '/api/public/auth/send-code': typeof ApiPublicAuthSendCodeRoute
  '/api/public/auth/session': typeof ApiPublicAuthSessionRoute
  '/api/public/auth/verify-code': typeof ApiPublicAuthVerifyCodeRoute
  '/api/public/email/send': typeof ApiPublicEmailSendRoute
  '/api/public/auth/google/callback': typeof ApiPublicAuthGoogleCallbackRoute
  '/api/public/auth/google/exchange': typeof ApiPublicAuthGoogleExchangeRoute
  '/api/public/auth/google/start': typeof ApiPublicAuthGoogleStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adopt-me': typeof AdoptMeRoute
  '/grow-a-garden': typeof GrowAGardenRoute
  '/mm2': typeof Mm2Route
  '/roblox-items': typeof RobloxItemsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/abandoned-cart': typeof ApiPublicAbandonedCartRoute
  '/api/public/account': typeof ApiPublicAccountRoute
  '/api/public/admin': typeof ApiPublicAdminRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
  '/api/public/wallet': typeof ApiPublicWalletRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
  '/api/public/auth/health': typeof ApiPublicAuthHealthRoute
  '/api/public/auth/send-code': typeof ApiPublicAuthSendCodeRoute
  '/api/public/auth/session': typeof ApiPublicAuthSessionRoute
  '/api/public/auth/verify-code': typeof ApiPublicAuthVerifyCodeRoute
  '/api/public/email/send': typeof ApiPublicEmailSendRoute
  '/api/public/auth/google/callback': typeof ApiPublicAuthGoogleCallbackRoute
  '/api/public/auth/google/exchange': typeof ApiPublicAuthGoogleExchangeRoute
  '/api/public/auth/google/start': typeof ApiPublicAuthGoogleStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adopt-me': typeof AdoptMeRoute
  '/grow-a-garden': typeof GrowAGardenRoute
  '/mm2': typeof Mm2Route
  '/roblox-items': typeof RobloxItemsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/abandoned-cart': typeof ApiPublicAbandonedCartRoute
  '/api/public/account': typeof ApiPublicAccountRoute
  '/api/public/admin': typeof ApiPublicAdminRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
  '/api/public/wallet': typeof ApiPublicWalletRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
  '/api/public/auth/health': typeof ApiPublicAuthHealthRoute
  '/api/public/auth/send-code': typeof ApiPublicAuthSendCodeRoute
  '/api/public/auth/session': typeof ApiPublicAuthSessionRoute
  '/api/public/auth/verify-code': typeof ApiPublicAuthVerifyCodeRoute
  '/api/public/email/send': typeof ApiPublicEmailSendRoute
  '/api/public/auth/google/callback': typeof ApiPublicAuthGoogleCallbackRoute
  '/api/public/auth/google/exchange': typeof ApiPublicAuthGoogleExchangeRoute
  '/api/public/auth/google/start': typeof ApiPublicAuthGoogleStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/adopt-me'
    | '/grow-a-garden'
    | '/mm2'
    | '/roblox-items'
    | '/auth/callback'
    | '/api/public/abandoned-cart'
    | '/api/public/account'
    | '/api/public/admin'
    | '/api/public/orders'
    | '/api/public/wallet'
    | '/auth/google/start'
    | '/api/public/auth/health'
    | '/api/public/auth/send-code'
    | '/api/public/auth/session'
    | '/api/public/auth/verify-code'
    | '/api/public/email/send'
    | '/api/public/auth/google/callback'
    | '/api/public/auth/google/exchange'
    | '/api/public/auth/google/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/adopt-me'
    | '/grow-a-garden'
    | '/mm2'
    | '/roblox-items'
    | '/auth/callback'
    | '/api/public/abandoned-cart'
    | '/api/public/account'
    | '/api/public/admin'
    | '/api/public/orders'
    | '/api/public/wallet'
    | '/auth/google/start'
    | '/api/public/auth/health'
    | '/api/public/auth/send-code'
    | '/api/public/auth/session'
    | '/api/public/auth/verify-code'
    | '/api/public/email/send'
    | '/api/public/auth/google/callback'
    | '/api/public/auth/google/exchange'
    | '/api/public/auth/google/start'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/adopt-me'
    | '/grow-a-garden'
    | '/mm2'
    | '/roblox-items'
    | '/auth/callback'
    | '/api/public/abandoned-cart'
    | '/api/public/account'
    | '/api/public/admin'
    | '/api/public/orders'
    | '/api/public/wallet'
    | '/auth/google/start'
    | '/api/public/auth/health'
    | '/api/public/auth/send-code'
    | '/api/public/auth/session'
    | '/api/public/auth/verify-code'
    | '/api/public/email/send'
    | '/api/public/auth/google/callback'
    | '/api/public/auth/google/exchange'
    | '/api/public/auth/google/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdoptMeRoute: typeof AdoptMeRoute
  GrowAGardenRoute: typeof GrowAGardenRoute
  Mm2Route: typeof Mm2Route
  RobloxItemsRoute: typeof RobloxItemsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicAbandonedCartRoute: typeof ApiPublicAbandonedCartRoute
  ApiPublicAccountRoute: typeof ApiPublicAccountRoute
  ApiPublicAdminRoute: typeof ApiPublicAdminRoute
  ApiPublicOrdersRoute: typeof ApiPublicOrdersRoute
  ApiPublicWalletRoute: typeof ApiPublicWalletRoute
  AuthGoogleStartRoute: typeof AuthGoogleStartRoute
  ApiPublicAuthHealthRoute: typeof ApiPublicAuthHealthRoute
  ApiPublicAuthSendCodeRoute: typeof ApiPublicAuthSendCodeRoute
  ApiPublicAuthSessionRoute: typeof ApiPublicAuthSessionRoute
  ApiPublicAuthVerifyCodeRoute: typeof ApiPublicAuthVerifyCodeRoute
  ApiPublicEmailSendRoute: typeof ApiPublicEmailSendRoute
  ApiPublicAuthGoogleCallbackRoute: typeof ApiPublicAuthGoogleCallbackRoute
  ApiPublicAuthGoogleExchangeRoute: typeof ApiPublicAuthGoogleExchangeRoute
  ApiPublicAuthGoogleStartRoute: typeof ApiPublicAuthGoogleStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adopt-me': {
      id: '/adopt-me'
      path: '/adopt-me'
      fullPath: '/adopt-me'
      preLoaderRoute: typeof AdoptMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grow-a-garden': {
      id: '/grow-a-garden'
      path: '/grow-a-garden'
      fullPath: '/grow-a-garden'
      preLoaderRoute: typeof GrowAGardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mm2': {
      id: '/mm2'
      path: '/mm2'
      fullPath: '/mm2'
      preLoaderRoute: typeof Mm2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roblox-items': {
      id: '/roblox-items'
      path: '/roblox-items'
      fullPath: '/roblox-items'
      preLoaderRoute: typeof RobloxItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/abandoned-cart': {
      id: '/api/public/abandoned-cart'
      path: '/api/public/abandoned-cart'
      fullPath: '/api/public/abandoned-cart'
      preLoaderRoute: typeof ApiPublicAbandonedCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/account': {
      id: '/api/public/account'
      path: '/api/public/account'
      fullPath: '/api/public/account'
      preLoaderRoute: typeof ApiPublicAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin': {
      id: '/api/public/admin'
      path: '/api/public/admin'
      fullPath: '/api/public/admin'
      preLoaderRoute: typeof ApiPublicAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/orders': {
      id: '/api/public/orders'
      path: '/api/public/orders'
      fullPath: '/api/public/orders'
      preLoaderRoute: typeof ApiPublicOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wallet': {
      id: '/api/public/wallet'
      path: '/api/public/wallet'
      fullPath: '/api/public/wallet'
      preLoaderRoute: typeof ApiPublicWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/start': {
      id: '/auth/google/start'
      path: '/auth/google/start'
      fullPath: '/auth/google/start'
      preLoaderRoute: typeof AuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/health': {
      id: '/api/public/auth/health'
      path: '/api/public/auth/health'
      fullPath: '/api/public/auth/health'
      preLoaderRoute: typeof ApiPublicAuthHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/send-code': {
      id: '/api/public/auth/send-code'
      path: '/api/public/auth/send-code'
      fullPath: '/api/public/auth/send-code'
      preLoaderRoute: typeof ApiPublicAuthSendCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/session': {
      id: '/api/public/auth/session'
      path: '/api/public/auth/session'
      fullPath: '/api/public/auth/session'
      preLoaderRoute: typeof ApiPublicAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/verify-code': {
      id: '/api/public/auth/verify-code'
      path: '/api/public/auth/verify-code'
      fullPath: '/api/public/auth/verify-code'
      preLoaderRoute: typeof ApiPublicAuthVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/send': {
      id: '/api/public/email/send'
      path: '/api/public/email/send'
      fullPath: '/api/public/email/send'
      preLoaderRoute: typeof ApiPublicEmailSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/google/callback': {
      id: '/api/public/auth/google/callback'
      path: '/api/public/auth/google/callback'
      fullPath: '/api/public/auth/google/callback'
      preLoaderRoute: typeof ApiPublicAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/google/exchange': {
      id: '/api/public/auth/google/exchange'
      path: '/api/public/auth/google/exchange'
      fullPath: '/api/public/auth/google/exchange'
      preLoaderRoute: typeof ApiPublicAuthGoogleExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/google/start': {
      id: '/api/public/auth/google/start'
      path: '/api/public/auth/google/start'
      fullPath: '/api/public/auth/google/start'
      preLoaderRoute: typeof ApiPublicAuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdoptMeRoute: AdoptMeRoute,
  GrowAGardenRoute: GrowAGardenRoute,
  Mm2Route: Mm2Route,
  RobloxItemsRoute: RobloxItemsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicAbandonedCartRoute: ApiPublicAbandonedCartRoute,
  ApiPublicAccountRoute: ApiPublicAccountRoute,
  ApiPublicAdminRoute: ApiPublicAdminRoute,
  ApiPublicOrdersRoute: ApiPublicOrdersRoute,
  ApiPublicWalletRoute: ApiPublicWalletRoute,
  AuthGoogleStartRoute: AuthGoogleStartRoute,
  ApiPublicAuthHealthRoute: ApiPublicAuthHealthRoute,
  ApiPublicAuthSendCodeRoute: ApiPublicAuthSendCodeRoute,
  ApiPublicAuthSessionRoute: ApiPublicAuthSessionRoute,
  ApiPublicAuthVerifyCodeRoute: ApiPublicAuthVerifyCodeRoute,
  ApiPublicEmailSendRoute: ApiPublicEmailSendRoute,
  ApiPublicAuthGoogleCallbackRoute: ApiPublicAuthGoogleCallbackRoute,
  ApiPublicAuthGoogleExchangeRoute: ApiPublicAuthGoogleExchangeRoute,
  ApiPublicAuthGoogleStartRoute: ApiPublicAuthGoogleStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
